Login and Registration
gorgrigoryan9955/Servers pull request #1
Opened 2019-04-24 12:32 UTC by gorgrigoryan9955

2019-04-24 12:46 UTC, narek118 requested changes

2019-04-24 12:46 UTC, narek118 commented on src/app/login/login.component.ts
> +    this.storageUsers = JSON.parse(this.storageUsers);
use tslint, this line should be one tab right,

2019-04-24 12:46 UTC, narek118 commented on src/app/login/login.component.ts
> +    this.currentUser = this.storageUsers.find((r) => {
this.storageUsers.find((user) => {

2019-04-24 12:46 UTC, narek118 commented on src/app/login/login.component.ts
> +    if (localStorage.getItem('Users')) {
delete unused codes

2019-04-24 12:46 UTC, narek118 commented on src/app/register/register.component.html
> +  <form [formGroup]="registerForm" #f >
don't use `#f`. Never use short uncertain variables. User #registerForm.

2019-04-24 12:46 UTC, narek118 commented on src/app/register/register.component.ts
>      console.log('aaaaaaa');
Remove all console.logs !!!

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/header/header.component.ts
> +    this.currentUserName = JSON.parse(localStorage.getItem('currentUser')).name;
You should have used localStorage service (service to work with localstorage). You should never add `JSON.parse(localStorage.getItem ` stuff in any component but instead use storageService.get('currentUser')

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-detail/server-detail.component.ts
> +    console.log(this.id, 'texsz');
remove

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-detail/server-detail.component.ts
> +          console.log(this.server, 'saaa');
remove

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-detail/server-detail.component.ts
> +          console.log('aaa');
remove

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-list/server-item/server-item.component.ts
> +    console.log(this.index, 'blablabla')
remove

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-list/server-item/server-item.component.ts
> +    // this.storageUsers = JSON.parse(this.storageUsers);
too much comments

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-list/server-list.component.ts
> +    this.types =  JSON.parse(localStorage.getItem('currentUser')) ? JSON.parse(localStorage.getItem('currentUser')).types : null;
should use a storage service

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-list/server-list.component.ts
> +    console.log(this.types, 'types');
remove

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-list/server-list.component.ts
> +      // console.log(item.serverType, 'items');
remove

2019-04-24 12:46 UTC, narek118 commented on src/app/register/register.component.ts
>      console.log('aaaaaaa');
removee

2019-04-24 12:46 UTC, narek118 commented on src/app/servers/server-list/server-list.component.ts
> +    console.log(this.userService, 'this.userService')
remove

2019-04-24 12:49 UTC, gorgrigoryan9955 commented on src/app/register/register.component.ts
>      console.log('aaaaaaa');
ok

2019-04-24 12:50 UTC, gorgrigoryan9955 commented on src/app/servers/server-list/server-list.component.ts
> +    this.types =  JSON.parse(localStorage.getItem('currentUser')) ? JSON.parse(localStorage.getItem('currentUser')).types : null;
should or must?

2019-04-25 07:46 UTC, narek118 approved these changes

2019-04-25 07:51 UTC, merged